# Generated by Django 3.1.7 on 2021-04-24 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotel.categorie'),
            preserve_default=False,
        ),
    ]
